FROM tomcat:8.0.20-jre8
MAINTAINER Dharma "dharmendra.singh4@cognizant.com"
curl -uadmin:AP4gmeCaE21YNBpqadHAbH7ShLh -O "http://ec2-34-212-9-250.us-west-2.compute.amazonaws.com:8081/artifactory/generic-local/qi-latest/qi-platform/QualityBot1.war"
COPY QualityBot1.war /usr/local/tomcat/webapps/QualityBot1.war
